const path = require('path');
const fs = require('fs');
const http = require('http');
const express = require('express');
const { WebSocketServer } = require('ws');

const PORT = process.env.PORT || 3000;
const MAX_PLAYERS = 4;
const TICK_MS = 50;
const MATCH_SECONDS = 180;
const PLAYER_HP = 100;
const RESPAWN_MS = 3000;
const HIT_RADIUS = 0.95;
const PLAYER_HEIGHT = 1.65;

const MAP_DEFS = {
  stadium: { half: 58, spawnR: 48 },
  lunch: { half: 48, spawnR: 40 },
  starbucks: { half: 43, spawnR: 35 },
  megacorp: { half: 53, spawnR: 44 },
  facility: { half: 62, spawnR: 52 },
};

// ===== Arsenal — keep in sync with public/js/weapons.js =====
const WEAPONS = {
  raygun: { name: 'RAY GUN', dmg: 40, cd: 200, mag: -1, reloadMs: 0, spread: 0, auto: true, range: 70, oneShot: false },
  klobber: { name: 'KLOBBER', dmg: 24, cd: 120, mag: 70, reloadMs: 1400, spread: 0.03, auto: true, range: 60, oneShot: false },
  dd: { name: 'DD SKULL', dmg: 72, cd: 470, mag: 21, reloadMs: 1600, spread: 0.006, auto: false, range: 80, oneShot: false },
  kf7: { name: 'KF7 SKULLETV', dmg: 36, cd: 150, mag: 90, reloadMs: 2000, spread: 0.016, auto: true, range: 75, oneShot: false },
  gold: { name: 'GOLDEN SKULLGUN', dmg: 250, cd: 850, mag: 5, reloadMs: 0, spread: 0, auto: false, range: 99, oneShot: true },
};
const GOLD_SHOTS = 5;
const PAD_RADIUS = 1.5;
const PAD_RESPAWN_MS = 22000;
const GOLD_LIVE_MS = 12000;
const GOLD_RESPAWN_MS = 30000;
const ARMOR_ABSORB = 0.55;
const STREAK_TEXT = { 2: 'DOUBLE KILL', 3: 'TRIPLE KILL', 4: 'KILLING SPREE' };

const GUN_PADS = {
  stadium: [
    [-27, -27, 'kf7'], [27, -27, 'dd'], [-27, 27, 'klobb'], [27, 27, 'armor'], [-21, -42, 'armor'], [21, 42, 'kf7'], [0, 0, 'dd'], [-14, 0, 'nade'], [14, 0, 'nade'],
  ],
  lunch: [
    [-22, -22, 'kf7'], [22, -22, 'dd'], [-22, 22, 'klobb'], [22, 22, 'armor'], [-17, -40, 'armor'], [17, 40, 'kf7'], [0, -18, 'dd'], [-10, 10, 'nade'], [10, 28, 'nade'],
  ],
  starbucks: [
    [-20, -20, 'kf7'], [26, -13, 'dd'], [-20, 20, 'klobb'], [20, 20, 'armor'], [-14, -31, 'armor'], [14, 31, 'kf7'], [0, 0, 'dd'], [-10, 8, 'nade'], [12, -6, 'nade'],
  ],
  megacorp: [
    [-25, -25, 'kf7'], [25, -25, 'dd'], [-25, 25, 'klobb'], [25, 25, 'armor'], [-13, -41, 'armor'], [13, 41, 'kf7'], [0, 26, 'dd'], [-12, 0, 'nade'], [12, 12, 'nade'],
  ],
  facility: [
    [-42, -30, 'kf7'], [42, 30, 'dd'], [-42, 30, 'klobb'], [42, -30, 'armor'], [0, -42, 'armor'], [0, 42, 'kf7'], [-26, 0, 'dd'], [26, 0, 'nade'], [0, 22, 'nade'],
  ],
};
const GOLD_SPOTS = {
  stadium: [0, 0],
  lunch: [0, 0],
  starbucks: [0, 12],
  megacorp: [0, 10],
  facility: [0, 0],
};

const FACILITY_SWITCHES = [[0, -28], [0, 28]];
const MAP_SHORTCUTS = {
  stadium: [{ x: 0, z: -47, toX: 0, toZ: 42 }, { x: 0, z: 47, toX: 0, toZ: -42 }],
  lunch: [{ x: -42, z: 0, toX: 38, toZ: 0 }, { x: 42, z: 0, toX: -38, toZ: 0 }],
  starbucks: [{ x: -37, z: -26, toX: 34, toZ: 26 }, { x: 37, z: 26, toX: -34, toZ: -26 }],
  megacorp: [{ x: -45, z: 5, toX: 41, toZ: -5 }, { x: 45, z: -5, toX: -41, toZ: 5 }],
  facility: [{ x: -50, z: 0, toX: 46, toZ: 0 }, { x: 50, z: 0, toX: -46, toZ: 0 }],
};
const FACILITY_REACTOR_RADIUS = 9;
const facilityRuntime = { disabledUntil: 0, switchReadyAt: 0 };

let mapId = 'facility';
let MAP_HALF = MAP_DEFS.facility.half;
let SPAWNS = cornerSpawns(MAP_DEFS.facility.spawnR);
/** Baked wall boxes per map — generated by tools/extract-colliders.mjs */
const MAP_COLLIDERS = JSON.parse(
  fs.readFileSync(path.join(__dirname, 'colliders.json'), 'utf8')
);
let colliders = MAP_COLLIDERS.facility || [];
/** @type {{id:string,x:number,z:number,w:string,kind:string,active:boolean,respawnAt:number}[]} */
let pads = [];
let goldPad = null;

function buildPads() {
  pads = (GUN_PADS[mapId] || []).map(([x, z, w], i) => ({
    id: `${mapId}-pad${i}`,
    x,
    z,
    w,
    kind: w === 'armor' ? 'armor' : w === 'nade' ? 'nade' : 'gun',
    active: true,
    respawnAt: 0,
  }));
  const g = GOLD_SPOTS[mapId] || [0, 0];
  goldPad = { x: g[0], z: g[1], spawned: false, active: false, respawnAt: 0 };
}

function resetPads(now) {
  match.startedAt = now;
  for (const pad of pads) {
    pad.active = true;
    pad.respawnAt = 0;
  }
  if (goldPad) {
    goldPad.spawned = false;
    goldPad.active = false;
    goldPad.respawnAt = 0;
  }
}

function cornerSpawns(r) {
  r = Math.round(r * 0.7);
  return [
    { x: -r, y: PLAYER_HEIGHT, z: -r, yaw: Math.PI / 4 },
    { x: r, y: PLAYER_HEIGHT, z: -r, yaw: (3 * Math.PI) / 4 },
    { x: -r, y: PLAYER_HEIGHT, z: r, yaw: -Math.PI / 4 },
    { x: r, y: PLAYER_HEIGHT, z: r, yaw: (-3 * Math.PI) / 4 },
  ];
}

function applyMap(id) {
  const def = MAP_DEFS[id] || MAP_DEFS.facility;
  mapId = MAP_DEFS[id] ? id : 'facility';
  MAP_HALF = def.half;
  SPAWNS = cornerSpawns(def.spawnR);
  colliders = MAP_COLLIDERS[mapId] || [];
  facilityRuntime.disabledUntil = 0;
  facilityRuntime.switchReadyAt = 0;
  buildPads();
  resetPads(Date.now());
}

const AGENTS = {
  skullpepe: { name: 'OG SKULL PEPE', color: '#6BAF6E', speedMul: 1.08, hpMul: 1.0 },
  daisy: { name: 'DAISY SKULL PEPE', color: '#5D9B62', speedMul: 1.0, hpMul: 0.95 },
  mini: { name: 'PUNK SPIKE PEPE', color: '#E5392D', speedMul: 1.2, hpMul: 0.8 },
  boss: { name: 'COURIER BAG PEPE', color: '#B56A4D', speedMul: 0.88, hpMul: 1.35 },
  drone: { name: 'TECH RAY PEPE', color: '#8E8E8E', speedMul: 1.05, hpMul: 0.9 },
  hazard: { name: 'HAZARD PEPE', color: '#F1C52A', speedMul: 1.02, hpMul: 1.05 },
};

const app = express();
app.get('/health', (_req, res) => {
  res.json({ ok: true, players: players.size, map: mapId });
});
app.use(
  express.static(path.join(__dirname, '..', 'public'), {
    etag: true,
    setHeaders(res, filePath) {
      if (/\.(js|mjs|css|html|json)$/i.test(filePath)) {
        res.setHeader('Cache-Control', 'no-cache, must-revalidate');
      } else {
        res.setHeader('Cache-Control', 'public, max-age=3600');
      }
    },
  })
);

const server = http.createServer(app);
const wss = new WebSocketServer({ server, path: '/ws', maxPayload: 4096 });

/** @type {Map<string, any>} */
const players = new Map();
let match = {
  started: false,
  endsAt: 0,
  startedAt: Date.now(),
  killFeed: [],
  mapId: 'facility',
};

function uid() {
  return Math.random().toString(36).slice(2, 10);
}

function freeSpawnIndex() {
  const used = new Set([...players.values()].map((p) => p.spawnIndex));
  for (let i = 0; i < SPAWNS.length; i++) {
    if (!used.has(i)) return i;
  }
  return Math.floor(Math.random() * SPAWNS.length);
}

function spawnPlayer(id, name, agentId) {
  const spawnIndex = freeSpawnIndex();
  const s = SPAWNS[spawnIndex];
  const agent = AGENTS[agentId] || AGENTS.skullpepe;
  const maxHp = Math.round(PLAYER_HP * agent.hpMul);
  return {
    id,
    name: String(name || agent.name)
      .replace(/[^a-z0-9 _-]/gi, '')
      .slice(0, 16)
      .toUpperCase() || agent.name,
    agentId: AGENTS[agentId] ? agentId : 'skullpepe',
    color: agent.color,
    speedMul: agent.speedMul,
    maxHp,
    x: s.x,
    y: s.y,
    z: s.z,
    yaw: s.yaw,
    pitch: 0,
    vx: 0,
    vy: 0,
    vz: 0,
    grounded: true,
    hp: maxHp,
    kills: 0,
    deaths: 0,
    tokens: 0,
    lives: 3,
    alive: true,
    shooting: false,
    lastShot: 0,
    respawnAt: 0,
    spawnShieldUntil: Date.now() + 1500,
    spawnIndex,
    connected: true,
    weapon: 'raygun',
    ammo: -1,
    reloadUntil: 0,
    armor: 0,
    lastKillAt: 0,
    streak: 0,
  };
}

function publicPlayer(p) {
  return {
    id: p.id,
    name: p.name,
    agentId: p.agentId,
    color: p.color,
    maxHp: p.maxHp,
    x: p.x,
    y: p.y,
    z: p.z,
    yaw: p.yaw,
    pitch: p.pitch,
    hp: p.hp,
    kills: p.kills,
    deaths: p.deaths,
    tokens: p.tokens,
    lives: p.lives,
    alive: p.alive,
    shooting: p.shooting,
    weapon: p.weapon,
    ammo: p.ammo,
    rt: Math.max(0, (p.reloadUntil || 0) - Date.now()),
    armor: p.armor || 0,
  };
}

function publicPickups() {
  const list = pads.map((pad) => ({
    x: round1(pad.x),
    z: round1(pad.z),
    w: pad.w,
    a: pad.active ? 1 : 0,
  }));
  if (goldPad && goldPad.spawned) {
    list.push({ x: round1(goldPad.x), z: round1(goldPad.z), w: 'gold', a: goldPad.active ? 1 : 0 });
  }
  return list;
}

function round1(n) {
  return Math.round(n * 10) / 10;
}

function snapshot(forId) {
  const now = Date.now();
  return {
    type: 'state',
    you: forId,
    timeLeft: match.started ? Math.max(0, Math.ceil((match.endsAt - Date.now()) / 1000)) : MATCH_SECONDS,
    started: match.started,
    players: [...players.values()].map(publicPlayer),
    killFeed: match.killFeed.slice(-6),
    maxPlayers: MAX_PLAYERS,
    pickups: publicPickups(),
    mapRuntime: mapId === 'facility'
      ? {
          mode: facilityMode(now),
          disabledFor: Math.max(0, facilityRuntime.disabledUntil - now),
        }
      : null,
  };
}

function broadcast(msg, exceptId) {
  const data = JSON.stringify(msg);
  for (const client of wss.clients) {
    if (client.readyState !== 1) continue;
    if (exceptId && client.playerId === exceptId) continue;
    client.send(data);
  }
}

function send(ws, msg) {
  if (ws.readyState === 1) ws.send(JSON.stringify(msg));
}

function pushFeed(text) {
  match.killFeed.push({ t: Date.now(), text });
  if (match.killFeed.length > 12) match.killFeed.shift();
}

function maybeStartMatch() {
  if (!match.started && players.size >= 1) {
    match.started = true;
    match.startedAt = Date.now();
    match.endsAt = Date.now() + MATCH_SECONDS * 1000;
    resetPads(match.startedAt);
    broadcast({ type: 'match', started: true, endsAt: match.endsAt, seconds: MATCH_SECONDS });
  }
}

function resetMatch() {
  match.started = false;
  match.endsAt = 0;
  match.killFeed = [];
  facilityRuntime.disabledUntil = 0;
  facilityRuntime.switchReadyAt = 0;
  for (const p of players.values()) {
    const s = SPAWNS[p.spawnIndex % SPAWNS.length];
    p.x = s.x;
    p.y = s.y;
    p.z = s.z;
    p.yaw = s.yaw;
    p.pitch = 0;
    p.hp = p.maxHp || PLAYER_HP;
    p.kills = 0;
    p.deaths = 0;
    p.tokens = 0;
    p.lives = 3;
    p.alive = true;
    p.respawnAt = 0;
    p.spawnShieldUntil = Date.now() + 1500;
    p.weapon = 'raygun';
    p.ammo = -1;
    p.reloadUntil = 0;
    p.armor = 0;
    p.lastKillAt = 0;
    p.streak = 0;
  }
  resetPads(Date.now());
  maybeStartMatch();
}

function clampArena(p) {
  const pad = 1.5;
  p.x = Math.max(-MAP_HALF + pad, Math.min(MAP_HALF - pad, p.x));
  p.z = Math.max(-MAP_HALF + pad, Math.min(MAP_HALF - pad, p.z));
}

function pointBlocked(x, z, r = 0.42) {
  for (const w of colliders) {
    const nx = Math.max(w.minX, Math.min(x, w.maxX));
    const nz = Math.max(w.minZ, Math.min(z, w.maxZ));
    const dx = x - nx;
    const dz = z - nz;
    if (dx * dx + dz * dz < r * r) return true;
  }
  return false;
}

// Swept axis-separated movement — mirrors client moveEntity, cannot cross walls
function moveWithColliders(p, dx, dz) {
  const dist = Math.hypot(dx, dz);
  const steps = Math.max(1, Math.ceil(dist / 0.2));
  for (let i = 0; i < steps; i++) {
    const tx = p.x + dx / steps;
    if (!pointBlocked(tx, p.z)) p.x = tx;
    else clampArena(p);
    const tz = p.z + dz / steps;
    if (!pointBlocked(p.x, tz)) p.z = tz;
    else clampArena(p);
  }
}

// Nearest wall hit along a ray — mirrors client castWalls slab test
function castWallsServer(ox, oy, oz, dx, dy, dz, maxDist) {
  let best = maxDist;
  const invx = dx !== 0 ? 1 / dx : 1e30;
  const invy = dy !== 0 ? 1 / dy : 1e30;
  const invz = dz !== 0 ? 1 / dz : 1e30;
  for (const w of colliders) {
    let tmin = 0;
    let tmax = best;
    let t1 = (w.minX - ox) * invx;
    let t2 = (w.maxX - ox) * invx;
    if (t1 > t2) [t1, t2] = [t2, t1];
    tmin = Math.max(tmin, t1);
    tmax = Math.min(tmax, t2);
    if (tmin > tmax) continue;
    t1 = (w.base - oy) * invy;
    t2 = (w.top - oy) * invy;
    if (t1 > t2) [t1, t2] = [t2, t1];
    tmin = Math.max(tmin, t1);
    tmax = Math.min(tmax, t2);
    if (tmin > tmax) continue;
    t1 = (w.minZ - oz) * invz;
    t2 = (w.maxZ - oz) * invz;
    if (t1 > t2) [t1, t2] = [t2, t1];
    tmin = Math.max(tmin, t1);
    tmax = Math.min(tmax, t2);
    if (tmax >= tmin && tmin >= 0 && tmin < best) best = tmin;
  }
  return best;
}

function startReload(p, now) {
  const W = WEAPONS[p.weapon] || WEAPONS.raygun;
  if (W.mag < 0 || p.reloadUntil || p.ammo === W.mag) return false;
  p.reloadUntil = now + W.reloadMs;
  return true;
}

function finishReloadIfDue(p, now) {
  if (p.reloadUntil && now >= p.reloadUntil) {
    p.reloadUntil = 0;
    p.ammo = (WEAPONS[p.weapon] || WEAPONS.raygun).mag;
  }
}

function spendGolden(p) {
  p.weapon = 'raygun';
  p.ammo = -1;
  p.reloadUntil = 0;
  pushFeed(`${p.name} BURNED THE GOLD`);
}

function applyDamage(target, dmg, ignoreArmor) {
  // Spawn protection — freshly dropped agents can't be insta-plasted
  if ((target.spawnShieldUntil || 0) > Date.now()) return;
  const absorbed = ignoreArmor ? 0 : Math.min(target.armor || 0, dmg * ARMOR_ABSORB);
  target.armor = Math.max(0, (target.armor || 0) - absorbed);
  target.hp -= dmg - absorbed;
}

function applyPlayerInput(p) {
  const input = p.input;
  p.shooting = false;
  if (!p.alive || !input || Date.now() - input.at > 250) return;
  p.yaw = input.yaw;
  p.pitch = input.pitch;
  const speed = (input.sprint ? 13.5 : 9.6) * (p.speedMul || 1);
  let mx = 0;
  let mz = 0;
  if (input.f) mz -= 1;
  if (input.b) mz += 1;
  if (input.l) mx -= 1;
  if (input.r) mx += 1;
  if (mx || mz) {
    const len = Math.hypot(mx, mz);
    mx = (mx / len) * 1.12;
    mz /= len;
    moveWithColliders(
      p,
      (mx * Math.cos(p.yaw) + mz * Math.sin(p.yaw)) * speed * (TICK_MS / 1000),
      (-mx * Math.sin(p.yaw) + mz * Math.cos(p.yaw)) * speed * (TICK_MS / 1000)
    );
  }
  if (input.shoot) tryShoot(p, input.click);
  input.click = false;
}

function facilityMode(now) {
  if (mapId !== 'facility' || !match.started || now < facilityRuntime.disabledUntil) return 0;
  const phase = Math.max(0, now - match.startedAt) % 12000;
  if (phase >= 8000) return 2;
  if (phase >= 6000) return 1;
  return 0;
}

function useFacilityControl(p, now) {
  if (mapId !== 'facility' || now < facilityRuntime.switchReadyAt) return false;
  const close = FACILITY_SWITCHES.some(([x, z]) => Math.hypot(p.x - x, p.z - z) <= 3.2);
  if (!close) return false;
  facilityRuntime.disabledUntil = now + 12000;
  facilityRuntime.switchReadyAt = now + 3000;
  broadcast({ type: 'mapEvent', event: 'reactorSuppressed', name: p.name });
  return true;
}

function eliminateByEnvironment(p, now) {
  p.hp = 0;
  p.alive = false;
  p.deaths += 1;
  p.lives = Math.max(0, p.lives - 1);
  p.respawnAt = now + RESPAWN_MS;
  const text = `REACTOR COOKED ${p.name}`;
  pushFeed(text);
  broadcast({ type: 'kill', killer: null, victim: p.id, text });
}

function tickFacility(now) {
  if (mapId !== 'facility') return;
  const mode = facilityMode(now);
  for (const p of players.values()) {
    if (!p.alive) continue;
    if (mode !== 2 || now < (p.mapHazardTickAt || 0)) continue;
    if (Math.hypot(p.x, p.z) > FACILITY_REACTOR_RADIUS) continue;
    if ((p.spawnShieldUntil || 0) > now) continue;
    p.mapHazardTickAt = now + 500;
    applyDamage(p, 14, true);
    if (p.hp <= 0) eliminateByEnvironment(p, now);
  }
}

function tickMapShortcuts(now) {
  const shortcuts = MAP_SHORTCUTS[mapId] || [];
  for (const p of players.values()) {
    if (!p.alive || now < (p.mapTeleportReadyAt || 0)) continue;
    for (const shortcut of shortcuts) {
      if (Math.hypot(p.x - shortcut.x, p.z - shortcut.z) > 1.55) continue;
      p.x = shortcut.toX;
      p.z = shortcut.toZ;
      p.mapTeleportReadyAt = now + 1400;
      break;
    }
  }
}

function tryShoot(shooter, click) {
  const now = Date.now();
  if (!shooter.alive) return;
  finishReloadIfDue(shooter, now);
  if (shooter.reloadUntil) return;
  const W = WEAPONS[shooter.weapon] || WEAPONS.raygun;
  if (!W.auto && !click) return;
  if (now - shooter.lastShot < W.cd) return;
  if (W.mag >= 0 && shooter.ammo <= 0) {
    startReload(shooter, now);
    return;
  }
  shooter.lastShot = now;
  shooter.shooting = true;
  shooter.spawnShieldUntil = 0; // firing drops your spawn protection
  if (W.mag >= 0) shooter.ammo -= 1;

  let dirX = Math.sin(shooter.yaw) * Math.cos(shooter.pitch);
  let dirY = Math.sin(shooter.pitch);
  let dirZ = -Math.cos(shooter.yaw) * Math.cos(shooter.pitch);
  if (W.spread > 0) {
    dirX += (Math.random() - 0.5) * W.spread;
    dirY += (Math.random() - 0.5) * W.spread * 0.6;
    dirZ += (Math.random() - 0.5) * W.spread;
    const len = Math.hypot(dirX, dirY, dirZ) || 1;
    dirX /= len;
    dirY /= len;
    dirZ /= len;
  }

  let best = null;
  let bestT = W.range;
  const wallT = castWallsServer(
    shooter.x, shooter.y, shooter.z,
    dirX, dirY, dirZ,
    W.range
  );

  for (const target of players.values()) {
    if (target.id === shooter.id || !target.alive) continue;
    // Ray vs sphere at chest
    const ox = shooter.x;
    const oy = shooter.y;
    const oz = shooter.z;
    const cx = target.x;
    const cy = target.y - 0.2;
    const cz = target.z;
    const fx = ox - cx;
    const fy = oy - cy;
    const fz = oz - cz;
    const b = fx * dirX + fy * dirY + fz * dirZ;
    const c = fx * fx + fy * fy + fz * fz - HIT_RADIUS * HIT_RADIUS;
    const disc = b * b - c;
    if (disc < 0) continue;
    const t = -b - Math.sqrt(disc);
    if (t > 0.2 && t < bestT && t <= wallT) {
      bestT = t;
      best = target;
    }
  }

  if (!best && wallT < W.range) {
    bestT = wallT; // bullets stop at walls — impact spark lands there
  }

  const impact = {
    x: shooter.x + dirX * Math.min(bestT, W.range),
    y: shooter.y + dirY * Math.min(bestT, W.range),
    z: shooter.z + dirZ * Math.min(bestT, W.range),
  };

  broadcast({
    type: 'shot',
    from: shooter.id,
    weapon: shooter.weapon,
    origin: { x: shooter.x, y: shooter.y, z: shooter.z },
    impact,
    hit: best ? best.id : null,
  });

  if (best) {
    applyDamage(best, W.dmg, W.oneShot);
    if (best.hp <= 0) {
      best.hp = 0;
      best.alive = false;
      best.deaths += 1;
      best.lives = Math.max(0, best.lives - 1);
      best.respawnAt = now + RESPAWN_MS;
      shooter.kills += 1;
      shooter.tokens += 5;
      const combo = now - (shooter.lastKillAt || 0) < 4000 ? (shooter.streak || 1) + 1 : 1;
      shooter.lastKillAt = now;
      shooter.streak = combo;
      let text = `${shooter.name} ⚡ ${best.name}`;
      const tag = STREAK_TEXT[combo] || (combo >= 5 ? 'RAMPAGE' : '');
      if (tag) text += ` · ${tag}!`;
      pushFeed(text);
      broadcast({
        type: 'kill',
        killer: shooter.id,
        victim: best.id,
        text,
      });
    } else {
      broadcast({ type: 'hit', target: best.id, hp: best.hp, by: shooter.id });
    }
  }

  if (W.mag >= 0 && shooter.ammo <= 0) {
    if (shooter.weapon === 'gold') spendGolden(shooter);
    else startReload(shooter, now);
  }
}

wss.on('connection', (ws) => {
  if (players.size >= MAX_PLAYERS) {
    send(ws, { type: 'error', message: 'SERVER FULL — 4 AGENTS MAX' });
    ws.close();
    return;
  }

  let playerId = null;

  ws.on('message', (raw) => {
    let msg;
    try {
      msg = JSON.parse(String(raw));
    } catch {
      return;
    }

    if (msg.type === 'join') {
      if (playerId) return;
      if (players.size === 0) {
        applyMap(msg.mapId || 'facility');
        match.mapId = mapId;
      }
      playerId = uid();
      ws.playerId = playerId;
      const p = spawnPlayer(playerId, msg.name, msg.agentId);
      players.set(playerId, p);
      maybeStartMatch();
      send(ws, {
        type: 'welcome',
        id: playerId,
        player: publicPlayer(p),
        maxPlayers: MAX_PLAYERS,
        mapId: match.mapId || mapId,
      });
      broadcast({ type: 'join', player: publicPlayer(p) }, playerId);
      send(ws, snapshot(playerId));
      return;
    }

    const p = playerId ? players.get(playerId) : null;
    if (!p) return;

    if (msg.type === 'reload') {
      startReload(p, Date.now());
      return;
    }

    if (msg.type === 'use') {
      if (p.alive) useFacilityControl(p, Date.now());
      return;
    }

    if (msg.type === 'input') {
      if (!p.alive) return;
      const yaw = Number(msg.yaw) || 0;
      const pitch = Math.max(-1.4, Math.min(1.4, Number(msg.pitch) || 0));
      p.input = {
        f: !!msg.f,
        b: !!msg.b,
        l: !!msg.l,
        r: !!msg.r,
        sprint: !!msg.sprint,
        shoot: !!msg.shoot,
        click: !!msg.click || !!p.input?.click,
        yaw,
        pitch,
        at: Date.now(),
      };
      return;
    }

    if (msg.type === 'ping') {
      send(ws, { type: 'pong', t: msg.t });
    }
  });

  ws.on('close', () => {
    if (!playerId) return;
    const p = players.get(playerId);
    players.delete(playerId);
    if (p) {
      pushFeed(`${p.name} LEFT THE FACILITY`);
      broadcast({ type: 'leave', id: playerId, name: p.name });
    }
    if (players.size === 0) {
      match.started = false;
      match.endsAt = 0;
      match.killFeed = [];
      match.mapId = 'facility';
      applyMap('facility');
    }
  });
});

setInterval(() => {
  const now = Date.now();

  for (const p of players.values()) applyPlayerInput(p);
  tickMapShortcuts(now);
  tickFacility(now);

  for (const p of players.values()) {
    finishReloadIfDue(p, now);
    if (!p.alive && p.respawnAt && now >= p.respawnAt) {
      if (p.lives <= 0) {
        p.lives = 3;
      }
      const s = SPAWNS[p.spawnIndex % SPAWNS.length];
      p.x = s.x + (Math.random() - 0.5) * 2;
      p.y = s.y;
      p.z = s.z + (Math.random() - 0.5) * 2;
      p.yaw = s.yaw;
      p.pitch = 0;
      p.hp = p.maxHp || PLAYER_HP;
      p.alive = true;
      p.respawnAt = 0;
      p.spawnShieldUntil = now + 1500; // spawn protection
      // Death strips specials back to the trusty RAY GUN
      p.weapon = 'raygun';
      p.ammo = -1;
      p.reloadUntil = 0;
      p.armor = 0;
      broadcast({ type: 'respawn', id: p.id, player: publicPlayer(p) });
    }
  }

  // Floor pads: respawn + proximity pickup (server owns positions)
  for (const pad of pads) {
    if (!pad.active && now >= pad.respawnAt) {
      pad.active = true;
    }
    if (!pad.active) continue;
    for (const p of players.values()) {
      if (!p.alive) continue;
      if (Math.hypot(p.x - pad.x, p.z - pad.z) > PAD_RADIUS) continue;
      let took = false;
      if (pad.kind === 'armor') {
        if ((p.armor || 0) < 95) {
          p.armor = 100;
          took = true;
        }
      } else {
        p.weapon = pad.w;
        p.ammo = (WEAPONS[pad.w] || WEAPONS.raygun).mag;
        p.reloadUntil = 0;
        took = true;
      }
      if (took) {
        pad.active = false;
        pad.respawnAt = now + PAD_RESPAWN_MS;
        broadcast({ type: 'pickup', by: p.id, name: p.name, kind: pad.kind, w: pad.w });
        break;
      }
    }
  }

  // The Golden Skullgun schedule
  if (goldPad && match.started) {
    if (!goldPad.spawned && now - match.startedAt >= GOLD_LIVE_MS) {
      goldPad.spawned = true;
      goldPad.active = true;
      broadcast({ type: 'goldlive' });
    } else if (goldPad.spawned && !goldPad.active && now >= goldPad.respawnAt) {
      goldPad.active = true;
      broadcast({ type: 'goldlive' });
    }
    if (goldPad.active) {
      for (const p of players.values()) {
        if (!p.alive) continue;
        if (Math.hypot(p.x - goldPad.x, p.z - goldPad.z) > PAD_RADIUS) continue;
        p.weapon = 'gold';
        p.ammo = GOLD_SHOTS;
        p.reloadUntil = 0;
        goldPad.active = false;
        goldPad.respawnAt = now + GOLD_RESPAWN_MS;
        broadcast({ type: 'pickup', by: p.id, name: p.name, kind: 'gold', w: 'gold' });
        break;
      }
    }
  }

  if (match.started && now >= match.endsAt) {
    const ranked = [...players.values()].sort((a, b) => b.kills - a.kills || a.deaths - b.deaths);
    broadcast({
      type: 'matchEnd',
      standings: ranked.map((p) => ({
        id: p.id,
        name: p.name,
        kills: p.kills,
        deaths: p.deaths,
        tokens: p.tokens,
      })),
    });
    setTimeout(resetMatch, 8000);
    match.started = false;
    match.endsAt = now + 999999;
  }

  for (const client of wss.clients) {
    if (client.readyState !== 1 || !client.playerId) continue;
    send(client, snapshot(client.playerId));
  }
}, TICK_MS);

server.listen(PORT, () => {
  console.log(`SKULLBOND online → http://localhost:${PORT}`);
  console.log(`WebSocket → ws://localhost:${PORT}/ws  (max ${MAX_PLAYERS})`);
});

